# -*- coding: utf-8 -*-
"""API for performing initial signup."""
from typing import Optional

from ...exceptions import ApiError
from ...tools import token_parse
from .. import json_api
from ..api_endpoints import ApiEndpoints
from ..models import ApiModel


class Signup(ApiModel):
    """API for endpoints that do not require api key and api token.

    Examples:
        * Check if initial signup has been done: :meth:`is_signed_up`
        * Perform initial signup: :meth:`signup`

    """

    @property
    def is_signed_up(self) -> bool:
        """Check if initial signup has been done.

        Examples:
            >>> signup = axonius_api_client.Signup(url="10.20.0.61")
            >>> signup.is_signed_up
            True
        """
        return self._get().value

    @property
    def system_status(self) -> json_api.signup.SystemStatus:
        """Get the status of the Axonius instance (started, ready, loading containers, ...)."""
        return self._status()

    def get_api_keys(self, user_name: str, password: str) -> dict:
        """Get the API key and token using user name and password credentials.

        Args:
            user_name: axonius username
            password: password for user_name
        """
        if not self.is_signed_up:
            raise ApiError("Initial signup not yet performed!")

        login = self._login("admin", "admin")
        bearer_token = login.document_meta["access_token"]
        return self._get_api_keys(bearer_token=bearer_token)

    def reset_api_keys(self, user_name: str, password: str) -> dict:
        """Reset the API key and token using user name and password credentials.

        Args:
            user_name: axonius username
            password: password for user_name
        """
        if not self.is_signed_up:
            raise ApiError("Initial signup not yet performed!")

        login = self._login("admin", "admin")
        bearer_token = login.document_meta["access_token"]
        response = self._reset_api_keys(bearer_token=bearer_token)
        self.CLIENT.HTTP.HEADERS_AUTH.update(response)
        return response

    def signup(self, password: str, company_name: str, contact_email: str) -> dict:
        """Perform the initial signup and get the API key and API secret of admin user.

        Examples:
            >>> signup = axonius_api_client.Signup(url="10.20.0.61")
            >>> data = signup.signup(
            ...     password="demo", company_name="Axonius", contact_email="jim@axonius.com"
            ... )
            >>> data
            {'api_key': 'xxxx', 'api_secret': 'xxxx'}

        Args:
            password: password for admin user
            company_name: name of company
            contact_email: email address of company contact
        """
        if self.is_signed_up:
            raise ApiError("Initial signup already performed!")

        response = self._perform(
            password=password, company_name=company_name, contact_email=contact_email
        )
        return response.to_dict()

    def validate_password_reset_token(self, token: str) -> bool:
        """Validate that a password reset token is valid."""
        token = token_parse(token)
        data = self._token_validate(token=token)
        return data.value

    def use_password_reset_token(
        self, token: str, password: str
    ) -> json_api.password_reset.UseResponse:
        """Use a password token reset link to change a users password.

        Args:
            token: password reset token
            password: password to set

        Notes:
            token can be generated by
            :meth:`axonius_api_client.api.system.system_users.SystemUsers.get_password_reset_link`
            or
            :meth:`axonius_api_client.api.system.system_users.SystemUsers.email_password_reset_link`

        Returns:
            name of user whose password was reset
        """
        token = token_parse(token)
        if not self.validate_password_reset_token(token=token):
            raise ApiError(f"Password reset token is not valid: {token}")

        data = self._token_use(token=token, password=password)
        return data

    def _status(self) -> json_api.signup.SystemStatus:
        """Direct API method to get the status of the overall system."""
        api_endpoint = ApiEndpoints.signup.status
        return api_endpoint.perform_request(client=self.CLIENT)

    def _get(self) -> json_api.generic.BoolValue:
        """Direct API method to get the status of initial signup."""
        api_endpoint = ApiEndpoints.signup.get
        return api_endpoint.perform_request(client=self.CLIENT)

    def _token_validate(self, token: str) -> json_api.password_reset.ValidateResponse:
        """Direct API method to validate a password reset token.

        Args:
            token: password reset token to validate
        """
        api_endpoint = ApiEndpoints.password_reset.validate
        request_obj = api_endpoint.load_request(token=token)
        return api_endpoint.perform_request(client=self.CLIENT, request_obj=request_obj)

    def _token_use(self, token: str, password: str) -> json_api.password_reset.UseResponse:
        """Direct API method to use a reset token to change a password.

        Args:
            token: password reset token
            password: password to set
        """
        api_endpoint = ApiEndpoints.password_reset.use
        request_obj = api_endpoint.load_request(token=token, password=password)
        return api_endpoint.perform_request(client=self.CLIENT, request_obj=request_obj)

    def _perform(
        self, password: str, company_name: str, contact_email: str
    ) -> json_api.signup.SignupResponse:
        """Direct API method to do the initial signup.

        Args:
            password: password to set to admin user
            company_name: company name
            contact_email: contact email
        """
        api_endpoint = ApiEndpoints.signup.perform
        request_obj = api_endpoint.load_request(
            company_name=company_name,
            new_password=password,
            confirm_new_password=password,
            contact_email=contact_email,
            user_name="admin",
            api_keys=True,
        )
        return api_endpoint.perform_request(client=self.CLIENT, request_obj=request_obj)

    def _login(self, user_name: str, password: str, remember_me: bool = False):
        """Direct API method to perform a login with username and password and get auth tokens.

        Args:
            user_name: axonius username to login with
            password: password for user_name
            remember_me: smh
        """
        api_endpoint = ApiEndpoints.signup.login
        request_obj = api_endpoint.load_request(
            user_name=user_name,
            password=password,
            remember_me=remember_me,
        )
        return api_endpoint.perform_request(client=self.CLIENT, request_obj=request_obj)

    def _get_api_keys(self, bearer_token: str) -> dict:
        """Get API key and token using a bearer token."""
        headers = {"authorization": f"Bearer {bearer_token}"}
        http_args = {"headers": headers, "headers_auth": False}
        api_endpoint = ApiEndpoints.signup.get_api_keys
        return api_endpoint.perform_request(client=self.CLIENT, http_args=http_args)

    def _reset_api_keys(self, bearer_token: str) -> dict:
        """Reset API key and token using a bearer token."""
        headers = {"authorization": f"Bearer {bearer_token}"}
        http_args = {"headers": headers, "headers_auth": False}
        api_endpoint = ApiEndpoints.signup.reset_api_keys
        return api_endpoint.perform_request(client=self.CLIENT, http_args=http_args)

    def __init__(self, url: Optional[str] = None, **kwargs):
        """Pass."""
        # backwards support for old Signup usage
        if url and not kwargs.get("client"):
            from ...connect import Connect

            kwargs.setdefault("key", "")
            kwargs.setdefault("secret", "")
            kwargs.setdefault("certwarn", False)
            kwargs["client"] = Connect(url=url, **kwargs)
        super().__init__(**kwargs)
